name: payselection_sdk
repository: https://github.com/stranger11/Payselection-Flutter-SDK
version: 1.0.0


environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  pointycastle: ^3.7.3
  uuid: ^4.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

